spring.application.name=employee-webservice
server.port=8080

spring.datasource.url=jdbc:h2:file:./data/employees-db;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.sql.init.mode=always
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
